language: go

# https://github.com/travis-ci/travis-ci/issues/9247
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "master"

go_import_path: github.com/OSSystems/auditmq

matrix:
  allow_failures:
    - go: master

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

before_install:
  - make vendor

install: true

script:
  - make test
